## Python Numpy Libraray

In [1]:
import numpy as np

In [12]:
d=[3,4,56,6]

In [13]:
a=np.array([d])
a

array([[ 3,  4, 56,  6]])

In [8]:
c=np.array([[3,3],[2,3],[3,3]])
c

array([[3, 3],
       [2, 3],
       [3, 3]])

In [10]:
type(c)

numpy.ndarray

In [11]:
a=np.array([])
a

array([], dtype=float64)

In [14]:
len(a)

1

In [23]:
c=np.array([[3,3],[2,3],[3,3]])
c

array([[3, 3],
       [2, 3],
       [3, 3]])

In [24]:
len(c)

3

In [25]:
c[0]

array([3, 3])

In [28]:
c=np.zeros(2)
c

array([0., 0.])

In [29]:
e=np.array([2,3,4,55,5])
e

array([ 2,  3,  4, 55,  5])

In [40]:
t=np.ones(5,dtype=np.int)
t

C:\Users\NEWBER~1\AppData\Local\Temp/ipykernel_12200/3451023555.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  t=np.ones(5,dtype=np.int)


array([1, 1, 1, 1, 1])

In [35]:
e

array([ 2,  3,  4, 55,  5])

In [36]:
t

array([0., 0., 0., 0., 0.])

In [38]:
y=np.arange(2,20,2)
y

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [39]:
e

array([ 2,  3,  4, 55,  5])

In [55]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
len(e)

3

In [64]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## how to reshape i just think that by multiply row and column we should get half of the array range

In [76]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

## Numpy practice session

In [77]:
name=np.array(['asim','mujtaba','ali'])
name

array(['asim', 'mujtaba', 'ali'], dtype='<U7')

In [78]:
price=np.array([23,45,67])
price

array([23, 45, 67])

In [79]:
type(price)

numpy.ndarray

In [80]:
type(name)

numpy.ndarray

In [81]:
len(name)

3

In [82]:
len(price)

3

In [83]:
price[1]

45

In [84]:
name[1]

'mujtaba'

In [86]:
price.mean()

45.0

In [87]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [88]:
 np.ones(3)

array([1., 1., 1.])

In [89]:
np.empty(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
np.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [91]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [92]:
  np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
np.arange(2,22,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [97]:
#linesapce mean aak sy 10 tak mn sy 4 numbera aye aur un ka distace equal hp
np.linspace(1,10,num=4)


array([ 1.,  4.,  7., 10.])

In [98]:
#specify datatype

In [99]:
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [100]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [101]:
#sorting ,function

In [102]:
f=np.array([3,4,5,6,7])
f

array([3, 4, 5, 6, 7])

In [103]:
v=np.array([56,45,5,64,7])
v

array([56, 45,  5, 64,  7])

In [107]:
q=np.append(f,v)
q

array([ 3,  4,  5,  6,  7, 56, 45,  5, 64,  7])

In [108]:
np.sort(q)

array([ 3,  4,  5,  5,  6,  7,  7, 45, 56, 64])

## 2D ARRAY

In [112]:
a2=np.array([[1,2,3,4,5],[23,3,32,11,3]])
a2

array([[ 1,  2,  3,  4,  5],
       [23,  3, 32, 11,  3]])

In [113]:
a1=np.array([[12,22,32,4,5],[223,23,32,11,63]])
a1

array([[ 12,  22,  32,   4,   5],
       [223,  23,  32,  11,  63]])

In [121]:
a1.ndim

2

In [114]:
np.concatenate((a2,a1),axis=1)

array([[  1,   2,   3,   4,   5,  12,  22,  32,   4,   5],
       [ 23,   3,  32,  11,   3, 223,  23,  32,  11,  63]])

In [115]:
np.concatenate((a2,a1),axis=0)

array([[  1,   2,   3,   4,   5],
       [ 23,   3,  32,  11,   3],
       [ 12,  22,  32,   4,   5],
       [223,  23,  32,  11,  63]])

In [117]:
s=np.array([[[12,2,21],[1,2,3]],[[2,3,4],[7,8,9]]])
s

array([[[12,  2, 21],
        [ 1,  2,  3]],

       [[ 2,  3,  4],
        [ 7,  8,  9]]])

In [118]:
np.array([[[12,2,21],[1,2,3],[7,8,9]]])

array([[[12,  2, 21],
        [ 1,  2,  3],
        [ 7,  8,  9]]])

In [119]:
# find demension
s.ndim

3

In [122]:
s.size

12

In [123]:
s.shape

(2, 2, 3)

In [132]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [133]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

## converting 1D ARRAY INTO 2D ARRAY

a=np.array([2,11,12,2])
a

In [135]:
a=np.array([2,11,12,2])
a

array([ 2, 11, 12,  2])

In [136]:
a[np.newaxis, :]

array([[ 2, 11, 12,  2]])

In [137]:
a.shape

(4,)

In [138]:
a[2:2]

array([], dtype=int32)

In [149]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [147]:
a+1

array([1, 2, 3, 4, 5, 6])

In [150]:
b=np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [151]:
a=a*b

array([ 0,  1,  4,  9, 16, 25])

In [156]:
np.mean(a)

2.5

In [152]:
sum(a)

15

In [155]:
a.mean()

2.5